### ISSUE TITLE
Caption for Windows and Linux

### ISSUE THREAD

**Issue by gielcobben** [gielcobben/caption#10]
I am currently working on making Caption for Windows and Linux. But because design is an important part of the end product, and I want Caption to be native in Windows and Linux as well, this will take a little time.

**Comment by SergioMP** [comment]
Great! Will follow this =)

**Comment by akashnimare** [comment]
@gielcobben let me know if you need any help.

**Comment by kralcak** [comment]
Thank you for Windows version

**Comment by nath5394** [comment]
Thanks I am interested un the Linux version.

**Comment by lecler-i** [comment]
Can you create a new branc for it ? So i can assist you on the linux version port

**Comment by LosEagle** [comment]
Why not just let users on other platforms use current version until redesign is done? The functionality will be identical on all platforms anyway. All that needs to be changed are some sass rules so it looks more native but I'm pretty sure that people will survive the app's design for while.

**Comment by gielcobben** [comment]
@LosEagle Well in that case just clone the repository modify `./package.js` and run: `npm run packer`. I don't have a Linux of Windows machine so I can't test it properly.

**Comment by macjabeth** [comment]
Looking forward to a linux release for this! I'd like to try running it locally but I'm unsure which bits to edit in `package.js`, and trying to use `npm start` without changing anything gives me an error:

```
0 info it worked if it ends with ok
1 verbose cli [ '/home/boonie/.nvm/versions/node/v7.9.0/bin/node',
1 verbose cli   '/home/boonie/.nvm/versions/node/v7.9.0/bin/npm',
1 verbose cli   'start' ]
2 info using npm@5.1.0
3 info using node@v7.9.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle caption@1.3.0~prestart: caption@1.3.0
6 info lifecycle caption@1.3.0~start: caption@1.3.0
7 verbose lifecycle caption@1.3.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle caption@1.3.0~start: PATH: /home/boonie/.nvm/versions/node/v7.9.0/lib/node_modules/npm/bin/node-gyp-bin:/home/boonie/Applications/Caption/node_modules/.bin:/home/boonie/.nvm/versions/node/v7.9.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/boonie/.rvm/bin:/snap/bin:/home/boonie/.rvm/bin:/home/boonie/.rvm/bin:/home/boonie/.rvm/bin
9 verbose lifecycle caption@1.3.0~start: CWD: /home/boonie/Applications/Caption
10 silly lifecycle caption@1.3.0~start: Args: [ '-c',
10 silly lifecycle   'cross-env NODE_ENV=production ./node_modules/.bin/electron ./' ]
11 silly lifecycle caption@1.3.0~start: Returned: code: 1  signal: null
12 info lifecycle caption@1.3.0~start: Failed to exec start script
13 verbose stack Error: caption@1.3.0 start: `cross-env NODE_ENV=production ./node_modules/.bin/electron ./`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/home/boonie/.nvm/versions/node/v7.9.0/lib/node_modules/npm/lib/utils/lifecycle.js:289:16)
13 verbose stack     at emitTwo (events.js:106:13)
13 verbose stack     at EventEmitter.emit (events.js:194:7)
13 verbose stack     at ChildProcess.<anonymous> (/home/boonie/.nvm/versions/node/v7.9.0/lib/node_modules/npm/lib/utils/spawn.js:40:14)
13 verbose stack     at emitTwo (events.js:106:13)
13 verbose stack     at ChildProcess.emit (events.js:194:7)
13 verbose stack     at maybeClose (internal/child_process.js:899:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
14 verbose pkgid caption@1.3.0
15 verbose cwd /home/boonie/Applications/Caption
16 verbose Linux 4.10.0-28-generic
17 verbose argv "/home/boonie/.nvm/versions/node/v7.9.0/bin/node" "/home/boonie/.nvm/versions/node/v7.9.0/bin/npm" "start"
18 verbose node v7.9.0
19 verbose npm  v5.1.0
20 error code ELIFECYCLE
21 error errno 1
22 error caption@1.3.0 start: `cross-env NODE_ENV=production ./node_modules/.bin/electron ./`
22 error Exit status 1
23 error Failed at the caption@1.3.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by gielcobben** [comment]
What it you try running `npm run dev`? :)

**Comment by macjabeth** [comment]
Thanks for the quick reply! ^_^

It doesn't fail to run, but nothing comes up after webpack is built. Here's the output: https://pastebin.com/raw/TkuesQ7S

Opening localhost:3000 also gives a "Cannot GET /" message.

**Comment by gielcobben** [comment]
Hmm.. weird. What node/npm and electron version are you using?

**Comment by macjabeth** [comment]
node v7.9.0
npm v5.1.0
electron v1.7.2

**Comment by gielcobben** [comment]
@macjabeth you have the right versions. I think it has something todo with the `setAboutPanelOptions()` function that's only available on mac. I just committed a possible fix. Can you pull the latest version and try again?

**Comment by macjabeth** [comment]
Sorry for the delayed response - my connection is very slow.

I seem to be having trouble during the initial setup now. `npm install` and `yarn install` both come up with an integrity error. This is the npm install error log:

```
...
20118 silly extract camelcase@3.0.0
20119 silly extract webpack-sources@0.1.5
20120 silly extract lodash.merge@3.3.2
20121 verbose unlock done using /home/boonie/.npm/_locks/staging-f820dca653c4e918.lock for /home/boonie/Applications/Caption/node_modules/.staging
20122 warn eslint-config-airbnb@12.0.0 requires a peer of eslint-plugin-import@^1.16.0 but none was installed.
20123 warn eslint-config-airbnb-base@8.0.0 requires a peer of eslint-plugin-import@^1.16.0 but none was installed.
20124 verbose type OperationalError
20125 verbose stack Error: sha1-RX078kvJYHwGrUsettqkrMrcIQg= integrity checksum failed when using sha1: wanted sha1-RX078kvJYHwGrUsettqkrMrcIQg= but got sha1-cA8MQo33za0ib4PPJSAjz4hIcso=. (4994 bytes)
20125 verbose stack     at Transform.on (/home/boonie/.nvm/versions/node/v7.9.0/lib/node_modules/npm/node_modules/ssri/index.js:275:19)
20125 verbose stack     at emitNone (events.js:91:20)
20125 verbose stack     at Transform.emit (events.js:188:7)
20125 verbose stack     at endReadableNT (_stream_readable.js:975:12)
20125 verbose stack     at _combinedTickCallback (internal/process/next_tick.js:80:11)
20125 verbose stack     at process._tickCallback (internal/process/next_tick.js:104:9)
20126 verbose cwd /home/boonie/Applications/Caption
20127 verbose Linux 4.10.0-28-generic
20128 verbose argv "/home/boonie/.nvm/versions/node/v7.9.0/bin/node" "/home/boonie/.nvm/versions/node/v7.9.0/bin/npm" "install"
20129 verbose node v7.9.0
20130 verbose npm  v5.3.0
20131 error code EINTEGRITY
20132 error sha1-RX078kvJYHwGrUsettqkrMrcIQg= integrity checksum failed when using sha1: wanted sha1-RX078kvJYHwGrUsettqkrMrcIQg= but got sha1-cA8MQo33za0ib4PPJSAjz4hIcso=. (4994 bytes)
20133 verbose exit [ 1, true ]
```

**Comment by fakeid30** [comment]
`@nirjhor-arch ➜ Caption rvm:(system) git:(master) ✗ npm run dev

> caption@1.3.0 dev /home/nirjhor/Downloads/Caption
> concurrently --kill-others "npm run hot-server" "npm run start-hot"

[0] npm
[0]  WARN invalid config loglevel="notice"
[1] npm
[1]  
[1] WARN invalid config loglevel="notice"
[0] 
[0] > caption@1.3.0 hot-server /home/nirjhor/Downloads/Caption
[0] > cross-env NODE_ENV=development node -r babel-register server.js
[0] 
[1] 
[1] > caption@1.3.0 start-hot /home/nirjhor/Downloads/Caption
[1] > cross-env HOT=1 NODE_ENV=development ./node_modules/.bin/electron -r babel-register -r babel-polyfill ./main.development
[1] 
[1] events.js:182
[1]       throw er; // Unhandled 'error' event
[1]       ^
[1] 
[1] Error: spawn ./node_modules/.bin/electron ENOENT
[1]     at exports._errnoException (util.js:1024:11)
[1]     at Process.ChildProcess._handle.onexit (internal/child_process.js:192:19)
[1]     at onErrorNT (internal/child_process.js:374:16)
[1]     at _combinedTickCallback (internal/process/next_tick.js:138:11)
[1]     at process._tickCallback (internal/process/next_tick.js:180:9)
[1]     at Function.Module.runMain (module.js:607:11)
[1]     at startup (bootstrap_node.js:158:16)
[1]     at bootstrap_node.js:575:3
[1] 
[1] npm
[1]  ERR! Linux 4.11.8-1-zen
[1] npm ERR! argv "/usr/bin/node" "/home/nirjhor/Downloads/Caption/node_modules/.bin/npm" "run" "start-hot"
[1] npm ERR! 
[1] node v8.2.1
[1] npm ERR! npm  v3.10.10
[1] npm 
[1] ERR! code ELIFECYCLE
[1] npm ERR! caption@1.3.0 start-hot: `cross-env HOT=1 NODE_ENV=development ./node_modules/.bin/electron -r babel-register -r babel-polyfill ./main.development`
[1] npm 
[1] ERR! Exit status 1
[1] npm ERR! 
[1] npm ERR!
[1]  Failed at the caption@1.3.0 start-hot script 'cross-env HOT=1 NODE_ENV=development ./node_modules/.bin/electron -r babel-register -r babel-polyfill ./main.development'.
[1] npm ERR! Make sure you have the latest version of node.js and npm installed.
[1] npm ERR!
[1]  If you do, this is most likely a problem with the caption package,
[1] npm ERR! not with npm itself.
[1] npm ERR! Tell the author that this fails on your system:
[1] npm
[1]  ERR!     cross-env HOT=1 NODE_ENV=development ./node_modules/.bin/electron -r babel-register -r babel-polyfill ./main.development
[1] npm ERR! You can get information on how to open an issue for this project with:
[1] npm 
[1] ERR!     npm bugs caption
[1] npm ERR! Or if that isn't available, you can get their info via:
[1] npm ERR!
[1]      npm owner ls caption
[1] npm ERR! There is likely additional logging output above.
[1] 
[1] npm ERR! Please include the following file with any support request:
[1] npm ERR!     /home/nirjhor/Downloads/Caption/npm-debug.log
[1] npm run start-hot exited with code 1
--> Sending SIGTERM to other processes..
[0] npm run hot-server exited with code 0
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! caption@1.3.0 dev: `concurrently --kill-others "npm run hot-server" "npm run start-hot"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the caption@1.3.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/nirjhor/.npm/_logs/2017-07-24T16_40_46_803Z-debug.log
`

What am I doing wrong ?

**Comment by isneezy** [comment]
I've managed to run `npm run dev` on linux with success, but I'm still getting some errors.

![caption](https://user-images.githubusercontent.com/8999039/29521524-3d9a7d78-8686-11e7-8215-0ac33e3e144b.png)


```shell
[0] webpack: Compiled successfully.
[1] npm run start-hot exited with code 0
--> Sending SIGTERM to other processes..
[0] Stopping dev server
[0] npm run hot-server exited with code null

npm ERR! Linux 4.4.0-89-generic
npm ERR! argv "/home/ivan/.nvm/versions/node/v6.11.2/bin/node" "/home/ivan/.nvm/versions/node/v6.11.2/bin/npm" "run" "dev"
npm ERR! node v6.11.2
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! caption@1.3.0 dev: `concurrently --kill-others "npm run hot-server" "npm run start-hot"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the caption@1.3.0 dev script 'concurrently --kill-others "npm run hot-server" "npm run start-hot"'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the caption package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     concurrently --kill-others "npm run hot-server" "npm run start-hot"
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs caption
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls caption
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ivan/repos/Caption/npm-debug.log

```

**Comment by mohsenkhanpour** [comment]
Any luck running it on a Windows?

**Comment by hamzaabdullah90** [comment]
Windows Please!

**Comment by gielcobben** [comment]
We're working on Caption V2. This version will be available on all platforms (Mac, Linux and Windows). More info soon :)

**Comment by fjeddy** [comment]
Caption is already non-native with the modified title bar.

**Comment by vernondegoede** [comment]
Hi! We launched Caption 2.0 for macOS, Windows and Linux yesterday. 

Download it here: https://getcaption.co
