### ISSUE TITLE
any reason caption would just stop finding subs?

### ISSUE THREAD

**Issue by skepticus** [gielcobben/Caption#13]
It worked for a few days, and now will raise nothing, either from the entry search or the drag and drop. Both SuperConverter and Subtitle Master find subs for files while Caption, apparently searches for, but never delivers. I've re-installed, trashed prefs, with no avail.

![grab 2017-02-15 at 17 27 50](https://cloud.githubusercontent.com/assets/136116/22998300/1f882aee-f3a4-11e6-9ecf-b0a2a7a8e2d9.jpg)

**Comment by MicroBenz** [comment]
Can you try to change language to any other language then change back to English and search again?

I guess it cause from #9 bug and already fixed in #11 (Maybe this patch will be in the next version.)

Here is a screenshot on my mac when change language to any other language then back to English.

![screen shot 2560-02-16 at 11 36 09 pm 1](https://cloud.githubusercontent.com/assets/9103800/23030556/ba7cc7c4-f4a0-11e6-9f5e-629bada65517.png)

**Comment by gielcobben** [comment]
It turns out that Opensubtitles had some problems the last couple of days. Opensubtitles is the only subtitle source for now. I'm working on adding multiple subtitles sources as we speak. so when one of them is down you still get results. 

You can find more about this feature right here:
https://github.com/gielcobben/Caption/issues/7

Thanks. 🙏🏻

**Comment by skepticus** [comment]
I'm pretty sure it was said:

> Can you try to change language to any other language then change back to English and search again?

You know, I actually tried that before listing the issue, to no avail.

I just tried that again, also with no joy. 

Here’s the shot from Subtitle Master, which successfully grabbed these four subs-



- and here’s the result from Caption-



- as you can see, no joy. It may be a problem with only using one source, because both Subtitle Master and SuperConverter (both of which found these four) use at least two.

Anyway, still can’t rely upon Caption for these, obviously.

> I guess it cause from #9 bug and already fixed in #11 (Maybe this patch will be in the next version.)

Looks like I need to wait for the next version then.

For me, this issue is not closed.

Thanks.

- Wade
